### ISSUE TITLE
IP address resolver times out a lot

### ISSUE THREAD

**Issue by petemahon** [MachineITSvcs/Cloudflare-DDNS-Update#1]
When this runs for me, frequently the IP address resolver (ipecho.net) just goes into a black hole, neither timing out or returning a value.

Would suggest resolving using a more resilient provider, such as:
export newip=$(dig TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'"' '{ print $2}'; echo)
or
export newip=$(dig +short myip.opendns.com @resolver1.opendns.com)

Other than that, very slick - thank you.

**Comment by MachineITSvcs** [comment]
Thank you for the recommendation. I have merged the pull request to remedy this.
