### ISSUE TITLE
what does your program do if two apache servers and your program are installed in two locations?

### ISSUE THREAD

**Issue by mingkan** [MachineITSvcs/Cloudflare-DDNS-Update#4]
what does your program do if two apache servers and your program are installed in two locations? will it be  performing failover? If I set it 1 min update period in both locations, will the program switch back-and-for every minute?

If I want another location as backup apache, can you as it as a backup ip?

**Comment by MachineITSvcs** [comment]
Unfortunately that is not how this script works. Although Cloudflare does
support multiple IPs for the same (sub)domain, this script will only update
(overwrite) the existing assignment, or create one if it does not already
exist. This means that if you decided to run it on two separate servers, it
is possible, but the recommended minimum ttyl is 5 minutes, meaning that
you could technically set each to run every 10 minutes, 5 minutes apart,
which would essentially be switching between servers every 5 minutes,
although I do not advise this practice.
