### ISSUE TITLE
Replace grep -P with jq

### ISSUE THREAD

**Issue by giffordj** [MachineITSvcs/Cloudflare-DDNS-Update#7]
I was using an embedded system, that uses busybox. Busybox grep doesn't support -P.

Modified to use
zone_identifier grep -Po '(?<="id":")[^"]*' | head -1 )  to jq -r '{"result"}[] | .[0] | .id'
record_identifier grep -Po '(?<="id":")[^"]*' | head -1 )  to jq -r '{"result"}[] | .[0] | .id'

**Comment by MachineITSvcs** [comment]
I am not familiar with jq but it appears to do the job. My only concern is whether jq is as common as grep or would require additional installation from the user. My installation has it already but that doesn't mean everyone's would. If you feel it would be a reasonable change to make, please consider putting this in a merge request.
